#!/usr/bin/env ruby

require 'thor'
require_relative 'analyze.rb'

class Txt2csv < Thor
  class_option :i, :banner => " Input file: this must be specified"
                   #:required => true
  class_option :o, :banner => " Output file: this must be specified"
                   #:required => true

  desc "analyze {-p | -s} -i File -o File", "analyze a file"
  # options :name_prefix, :aliases => :p
  # options :name_suffix, :aliases => :s
  def analyze
   input = options[:i]
   output = options[:o]
   fix = '-p'
   Analyze.new(input, output, fix)
  end

  desc "convert -p File -s File -i File -o File", "convert a file"
  # options :name_prefix, :aliases => :p
  # options :name_suffix, :aliases => :s
  def convert
    puts "option i works!" if options[:i]
  end

end

Txt2csv.start
